### ISSUE TITLE
评论表数据库设计

### ISSUE THREAD

**Issue by chenquan** [opensourceai/go-api-service#24]
要求：

1. 用户可以评论主题帖
2. 用户可以评论其他用户的评论

**注：** 上网查询一下相关的资料，不同设计方案的利弊，在本`Issues`讨论

**Comment by TinyHaHa** [comment]
表字段

字段说明

id  主键

topic_id  主题id

~~topic_type  主题类型~~

content  评论内容

from_uid  评论用户id

to_uid  评论目标用户id

**Comment by chenquan** [comment]
主题类型这个字段有什么作用呢？

**Comment by TinyHaHa** [comment]
我把它改成了板块名，可以不要这栏



---原始邮件---
发件人: "Chen Quan"<notifications@github.com&gt;
发送时间: 2020年3月15日(周日) 中午1:12
收件人: "opensourceai/go-api-service"<go-api-service@noreply.github.com&gt;;
抄送: "Nansen"<1145445922@qq.com&gt;;"Assign"<assign@noreply.github.com&gt;;
主题: Re: [opensourceai/go-api-service] 评论表数据库设计 (#24)




 
主题类型这个字段有什么作用呢？

**Comment by chenquan** [comment]
> 表字段
> 
> 字段说明
> 
> id 主键
> 
> topic_id 主题id
> 
> ~topic_type 主题类型~
> 
> content 评论内容
> 
> from_uid 评论用户id
> 
> to_uid 评论目标用户id
@TinyHaHa 那就是这样咯

**Comment by chenquan** [comment]
![image](https://user-images.githubusercontent.com/20548053/76862525-36fc2280-6899-11ea-9a02-28a1301c9afa.png)
这个表是你创建的吗？ @TinyHaHa 
#10 其他的字段呢，不设置外键。。。。。。
`board_id`是什么意思？
修正：
`comment_id` -> `id`

**Comment by chenquan** [comment]
SQL语句：
```sql
/*
 Navicat Premium Data Transfer

 Source Server         : 101.132.38.180
 Source Server Type    : MySQL
 Source Server Version : 50728
 Source Host           : 101.132.38.180:3306
 Source Schema         : hive-dev

 Target Server Type    : MySQL
 Target Server Version : 50728
 File Encoding         : 65001

 Date: 17/03/2020 22:39:52
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for hive_comment
-- ----------------------------
DROP TABLE IF EXISTS `hive_comment`;
CREATE TABLE `hive_comment`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `comment_content` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '评论内容',
  `post_id` int(11) NOT NULL COMMENT '主题ID',
  `from_uid` int(11) NOT NULL COMMENT '评论者ID',
  `to_uid` int(11) NOT NULL COMMENT '被评论者ID',
  `created_on` int(11) NOT NULL DEFAULT 0 COMMENT '发布时间',
  `modified_on` int(11) NOT NULL DEFAULT 0 COMMENT '最近一次更新时间',
  `deleted_on` int(11) NOT NULL DEFAULT 0 COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

```
