### ISSUE TITLE
用户信息修改

### ISSUE THREAD

**Issue by chenquan** [opensourceai/go-api-service#35]
要求:

- [ ] 1. 用户可以修改自身的密码[password]

- [ ] 2. 用户可以修改自身的信息,可以修改字段为:
    - name
    - description
    - sex
    - email
    - web_site
    - company
    - position

**Comment by TinyHaHa** [comment]
get



---原始邮件---
发件人: "Chen Quan"<notifications@github.com&gt;
发送时间: 2020年3月15日(周日) 中午1:40
收件人: "opensourceai/go-api-service"<go-api-service@noreply.github.com&gt;;
抄送: "Nansen"<1145445922@qq.com&gt;;"Assign"<assign@noreply.github.com&gt;;
主题: Re: [opensourceai/go-api-service] 用户信息修改 (#35)




 
Assigned #35 to @TinyHaHa.
